SoraUnitySdkSamples/Assets/SoraSample.cs

Inspectorからコーデックを選択できるようにしました。

Video Codecを選択可能にする

---

README.md
SoraUnitySdkSamples/Assets/SoraSample.cs
install.ps1
install.sh

- GetStats を利用する処理を追加 @melpon 
- Sora Unity SDK 2020.6.1 を利用するように修正 @torikizi 
- README.md を最新化 @torikizi

Sora Unity SDK 2020.6.1 を利用する

---

SoraUnitySdkSamples/Assets/Scenes/multi_sendonly.unity
SoraUnitySdkSamples/Assets/Scenes/multi_sendrecv.unity
SoraUnitySdkSamples/Assets/Scenes/sendonly.unity
SoraUnitySdkSamples/Assets/Sphere_Material.mat
SoraUnitySdkSamples/Assets/Sphere_Material.mat.meta

- sendonly multi_sendonly multi_sendrecv 内の Sphere に Material を追加

シーン内の Sphere に Material を追加

---

install.ps1
install.sh

- install.sh を 2020.9 を利用するようにアップデートしました
- install.ps1 を 2020.9 を利用するようにアップデートしました

Sora Unity SDK を 2020.9 にアップデート

---

install.ps1
install.sh

- install.sh と install.ps1 を 2020.10 を利用するようにアップデートしました

Sora Unity SDK を 2020.10 にアップデート

---

install.ps1
install.sh

- install.sh を Sora Unity SDK 2021.2 を使用するようにしました
- install.ps1 を Sora Unity SDK 2021.2 を使用するようにしました

Sora Unity SDK 2021.2 を使用する

---

SoraUnitySdkSamples/Assets/SoraSample.cs

- SoraSample.cs にSpotlightFocusRid と SpotlightUnfocusRid を追加しました

SpotlightFocusRid と SpotlightUnfocusRid に対応

---

SoraUnitySdkSamples/Assets/SoraSample.cs

- SoraSample.cs に ClientId を追加しました

ClientId に対応

---

SoraUnitySdkSamples/Assets/SoraSample.cs

- 接続時に SimulcastRid を指定できるようにしました

SimulcastRid に対応

---

SoraUnitySdkSamples/Assets/SoraSample.cs

プッシュ通知をログに出力するように修正

---

SoraUnitySdkSamples/Assets/Scenes/multi_recvonly.unity
SoraUnitySdkSamples/Assets/Scenes/multi_sendonly.unity
SoraUnitySdkSamples/Assets/Scenes/multi_sendrecv.unity
SoraUnitySdkSamples/Assets/Scenes/recvonly.unity
SoraUnitySdkSamples/Assets/Scenes/sendonly.unity
SoraUnitySdkSamples/Assets/SoraSample.cs
copy.ps1
copy.sh
install.ps1
install.sh

サンプルで DataChannel シグナリングとメッセージングが利用可能になります。
破壊的変更があるので、対応したバージョンの Sora Unity SDK がリリースされた後、`install.sh`, `install.bat` のバージョンを書き換えた上でマージする必要があります。

DataChannel を使ったシグナリングとメッセージングに対応

---

install.ps1
install.sh

- install.sh と install.ps1 に Generated フォルダのコピーを追加しました。

Generated フォルダのコピーが含まれていなかったため追加

---

install.ps1
install.sh

- install.sh を Sora Unity SDK 2021.3.1 を使用するように修正
- install.ps1 を Sora Unity SDK 2021.3.1 を使用するように修正

Sora Unity SDK 2021.3.1 を使用する

---

SoraUnitySdkSamples/.gitignore

- Plugins の Linux フォルダに不要なファイルが残っていたため削除しました

不要なファイルを削除

---

README.md

手順を詳細化しました。Unity の用語に慣れていない箇所もあるのでおかしなところがないか確認をお願いできますか。

サンプルの実行方法の説明を詳細化する

---

README.md

Ubuntu の必要パッケージの追加と諸注意の削除を行なっています。
パッケージ追加については以下の PR と書き方を合わせて変更する可能性があります。
https://github.com/shiguredo/sora-unity-sdk/pull/54

README.md を更新する

---

README.md

サンプルの利用手順をコマンドを追加するなど少しだけ見直してみました。
手順が分かりにくくなっている等、もし気になる点あればコメントいただけますか。

[doc] サンプル利用手順を更新する

---

SoraUnitySdkSamples/Assets/Scenes/multi_sendonly.unity
SoraUnitySdkSamples/Assets/Scenes/multi_sendrecv.unity
SoraUnitySdkSamples/Assets/Scenes/sendonly.unity
SoraUnitySdkSamples/Assets/SoraSample.cs

映像と音声のミュートを Send のシーンに追加しました。
iOS / Android / macOS / Windows / Linux での動作確認済みです。

映像と音声のミュートを追加

---

SoraUnitySdkSamples/Assets/SoraSample.cs

Sora C++ SDK の Lyra パラメータ変更に追従する

---

CHANGES.md
SoraUnitySdkSamples/Assets/SoraSample.cs

CodecParams を追加しました。
手元では動作を確認しました。

CodecParams を追加

---

SoraUnitySdkSamples/Assets/SoraSample.cs

forwardingfilter を追加しました。
設定が難しいので Inspector で設定できるようにしました。
[![Image from Gyazo](https://i.gyazo.com/986b7ad88943844377f2e9fbea767aa1.png)](https://gyazo.com/986b7ad88943844377f2e9fbea767aa1)

forwardingfilter を追加

---

SoraUnitySdkSamples/Assets/Scenes/multi_sendonly.unity
SoraUnitySdkSamples/Assets/Scenes/multi_sendrecv.unity
SoraUnitySdkSamples/Assets/Scenes/sendonly.unity
SoraUnitySdkSamples/Assets/SoraSample.cs
copysdk.py

https://github.com/shiguredo/sora-unity-sdk-samples/pull/48 に切り替えボタンを追加したものになります。

接続中のカメラ切り替え機能とボタンを追加

---

SoraUnitySdkSamples/Assets/SoraSample.cs

useHardwareEncoder をサンプルに追加しました。
動作確認まで完了済みです。

useHardwareEncoder パラメータを追加

---

CHANGES.md
SoraUnitySdkSamples/.gitignore
SoraUnitySdkSamples/Assets/Plugins/SoraUnitySdk/android/Sora.aar.meta
SoraUnitySdkSamples/Assets/Scenes/multi_sendrecv.unity
SoraUnitySdkSamples/Assets/SoraSample.cs

multi_sendrecv シーンにハンズフリーボタンを追加します。

ハンズフリーボタンを追加

---

SoraUnitySdkSamples/Assets/SoraSample.cs

Sendonly の場合ハンズフリーを使用しないように修正。
手元では動作確認済み。

ハンズフリーは送信のみの場合は使用しないようにする
